# Generated by Django 4.1.7 on 2024-12-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewebtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('build_manufacturer', models.CharField(max_length=100)),
                ('build_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transitagency',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transitagency',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transitagency',
            name='customer_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transitagency',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transitagency',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
